### ISSUE TITLE
What is the point/purpose of this tool?

### ISSUE THREAD

**Issue by justingoldberg** [kjake/docker-veeam-backup-repository#1]
What is the point/purpose of this tool?

Is it mainly for non-Windows shops? Is it sort of a _Veeam One Lite_?

**Comment by kjake** [comment]
Yup, it's for non-Windows - it basically running vPower NFS via SSH... I think, been awhile since I looked at it.  Looks like a Linux server.
https://helpcenter.veeam.com/docs/backup/vsphere/add_linux_server.html?ver=110

Using Docker means that you're able to be less impacted by the base OS.  In fact, I run this in a container OS, called RancherOS - all services are generally containerized.  This allows me to map the file system only to this container, and upgrade the base OS without too much impact.  Unfortunately, RancherOS is becoming unmaintained, so I will probably replace this backup repo with something else.

I don't have Veeam One and haven't used it - I only have B&R.  Can't really comment on whether this has overlap with Veeam One.
